"""empty message

Revision ID: d216a621fa50
Revises: cb6d54a6b8cc
Create Date: 2018-05-27 21:03:04.870508

"""

# revision identifiers, used by Alembic.
revision = 'd216a621fa50'
down_revision = 'cb6d54a6b8cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('allow_recurso', sa.Boolean(), nullable=False,
                                      server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedido', 'allow_recurso')
    # ### end Alembic commands ###
