"""empty message

Revision ID: 3b7f58ea72e7
Revises: d216a621fa50
Create Date: 2018-05-28 14:22:24.283493

"""

# revision identifiers, used by Alembic.
revision = '3b7f58ea72e7'
down_revision = 'd216a621fa50'

import enum
from alembic import op
import sqlalchemy as sa


def upgrade():
    bind = op.get_bind()
    types = enum.Enum('UserMessageTypes', 'pergunta recurso')
    sa.Enum(types).create(bind)
    op.add_column(
        'pre_pedido',
        sa.Column(
            'type', sa.Enum(name='usermessagetypes'), nullable=False,
            server_default=types.pergunta.name))
    op.alter_column(
        'pre_pedido', 'pedido_id', existing_type=sa.INTEGER(), nullable=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'pre_pedido', 'pedido_id', existing_type=sa.INTEGER(), nullable=True)
    op.drop_column('pre_pedido', 'type')
    # ### end Alembic commands ###
