"""empty message

Revision ID: 6545c2afafa1
Revises: a952dc8a28e9
Create Date: 2018-05-24 19:19:40.086422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6545c2afafa1'
down_revision = 'a952dc8a28e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execucao_history', sa.Column('notification_sent', sa.Boolean(),
                                                nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execucao_history', 'notification_sent')
    # ### end Alembic commands ###
