"""empty message

Revision ID: a952dc8a28e9
Revises: 
Create Date: 2018-05-24 18:47:26.150946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a952dc8a28e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_execucao_point', table_name='execucao')
    op.create_foreign_key(None, 'execucao_history', 'execucao', ['code'], ['code'])
    op.drop_index('idx_regions_geo', table_name='regions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_regions_geo', 'regions', ['geo'], unique=False)
    op.drop_constraint(None, 'execucao_history', type_='foreignkey')
    op.create_index('idx_execucao_point', 'execucao', ['point'], unique=False)
    # ### end Alembic commands ###
